server:
  ssl:
    key-store: classpath:server-keystore.jks
    key-store-password: changeit
    key-alias: serverleaf
    key-store-type: JKS
    trust-store: classpath:server-truststore.jks
    trust-store-password: changeit
    client-auth: need
