spring:
  ssl:
    bundle:
      jks:
        book-server:
          truststore:
            location: classpath:client-truststore.jks
            password: changeit
          keystore:
            location: classpath:client-keystore.jks
            type: JKS
            password: changeit
          key:
            alias: clientLeaf
  main:
    banner-mode: off
logging:
  level:
    root: warn
