spring:
  ssl:
    bundle:
      jks:
        book-server:
          truststore:
            location: /home/pvale/dev/code/Personal/experimenting-with-spring/spring-ssl/client-truststore.jks
            password: changeit
          keystore:
            location: /home/pvale/dev/code/Personal/experimenting-with-spring/spring-ssl/client-keystore.jks
            type: JKS
            password: changeit
          key:
            alias: clientLeaf
  main:
    banner-mode: off
logging:
  level:
    root: warn
